export const categories: { [key: string]: {[key: string]: string}} = {
  fashion: { display: 'fashion' },
  nature: { display: 'nature' },
  backgrounds: { display: 'backgrounds' },
  science: { display: 'science' },
  education: { display: 'education' },
  people: { display: 'people' },
  feelings: { display: 'feelings' },
  religion: { display: 'religion' },
  health: { display: 'health' },
  places: { display: 'places' },
  animals: { display: 'animals' },
  industry: { display: 'industry' },
  food: { display: 'food' },
  computer: { display: 'computer' },
  sports: { display: 'sports' },
  ansportation: { display: 'ansportation' },
  travel: { display: 'travel' },
  buildings: { display: 'buildings' },
  business: { display: 'business' },
  music: { display: 'music'},
}
