export const categories: { [key: string]: {[key: string]: string}} = {
  fashion: { display: 'Fashion' },
  nature: { display: 'Nature' },
  backgrounds: { display: 'Backgrounds' },
  science: { display: 'Science' },
  education: { display: 'Education' },
  people: { display: 'People' },
  feelings: { display: 'Feelings' },
  religion: { display: 'Religion' },
  health: { display: 'Health' },
  places: { display: 'Places' },
  animals: { display: 'Animals' },
  industry: { display: 'Industry' },
  food: { display: 'Food' },
  computer: { display: 'Computer' },
  sports: { display: 'Sports' },
  transportation: { display: 'Transportation' },
  travel: { display: 'Travel' },
  buildings: { display: 'Buildings' },
  business: { display: 'Business' },
  music: { display: 'Music'},
}
